export enum ContentTypeEnum {
    IMAGE_JPEG = 'IMAGE/JPEG',
    IMAGE_PNG = 'IMAGE/PNG',
    VIDEO_MP4 = 'VIDEO/MP4',
    APPLICATION_PDF = 'APPLICATION/PDF',
    APPLICATION_MSWORD = 'APPLICATION/MSWORD', // MS Word (.doc, .docx)
}
